### PR TITLE
Fix Jenkinsfile capitalization

### PR DESCRIPTION
**Pull request by ghost**
`Jenkinsfile` needs to be capitalized for it to be recognized by Jenkins

As an aside, It's generally a good idea to do a `git config --global --bool core.ignorecase false` so that git will recognize `Jenkinsfile` and `jenkinsfile` as different files, because otherwise git will not realize that the filename actually changed, and `git status` won't show any changes.

You might need to configure this for each repo (i.e. `git config --local --bool core.ignorecase false` ) depending on the defaults git uses when making new repos.

---
@jmason-va

### CODE REVIEW

**Review by bradsk88 — APPROVED** [review]

**Comment by jredl-va** [comment]
looks good, but should we move this repo into the vendasta organization?

**Comment by jmason-va** [comment]
@jredl-va I agree, I didn't want to bloat the vendasta repo unless other people were actually going to use it 🤷‍♂️, we can/should move it in now 👍

**Review by jmason-va — APPROVED** [review]
:p

**Review by bjohnson-va — APPROVED** [review]
Apparently my review doesn't "count" from my other account :\\
(Nor does this?)

**Comment by ghost** [comment]
Merging this for now, ping me if you'd like a hand with migrating this to the GH org

edit: ah can't merge, feel free to do so

**Pull request merged**
